"""
Generates flow_diagram.md from the compiled LangGraph StateGraph.

Run from the project root:
    python scripts/export_graph.py

This ensures the architecture diagram is always derived from the real compiled graph
rather than hand-drawn — any structural change in build.py is reflected automatically.
"""

import sys
from pathlib import Path

# Make the project root importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.graph.build import build_graph

OUTPUT = Path(__file__).resolve().parent.parent / "flow_diagram.md"


def main():
    compiled = build_graph()
    mermaid = compiled.get_graph().draw_mermaid()

    OUTPUT.write_text(
        f"# Multimodal Agent — Graph Architecture\n\n"
        f"*Auto-generated by `scripts/export_graph.py`. Do not edit by hand.*\n\n"
        f"```mermaid\n{mermaid}\n```\n",
        encoding="utf-8",
    )
    print(f"Wrote Mermaid diagram to {OUTPUT}")


if __name__ == "__main__":
    main()
